services:
  postgresql:
    image: postgres:17.2-alpine
    container_name: impulse_analytics_db
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data:rw

  redis:
    image: redis:6.2-alpine
    command: [ 'redis-server', '--save' ]
    ports:
      - ${REDIS_PORT}:6379

networks:
  default:
